services:
  frontend:
    build:
      context: ./frontend
      args:
        # Vite reads only VITE_* at build time
        VITE_API_BASE_URL: "http://localhost:8080"
        VITE_API_TOKEN: "your-secret-token"
    ports: ["3000:80"]
    depends_on: [backend]

  backend:
    build: ./backend
    ports: ["8080:8080"]
    environment:
      PORT: "8080"
      # DB config
      DB_HOST: mysql
      DB_PORT: "3306"
      DB_USER: root
      DB_PASSWORD: password
      DB_NAME: crawler
      # API auth & CORS
      AUTH_TOKEN: "your-secret-token"
      ALLOWED_ORIGIN: "http://localhost:3000"
    depends_on:
      mysql:
        condition: service_healthy

  mysql:
    image: mysql:8
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: crawler
    volumes:
      - mysql_data:/var/lib/mysql
      - ./backend/init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-ppassword"]
      interval: 5s
      timeout: 5s
      retries: 20

volumes:
  mysql_data: {}
